base_url = "https://boykush.github.io/"

title = "Kush's Home"
description = "ソフトウェアエンジニア。日々は続く"

default_language = "ja"

theme = "apollo"

compile_sass = true
generate_feeds = true
minify_html = true

taxonomies = [
  { name = "tags", feed = true }
]

[markdown]
highlight_code = true
highlight_theme = "nord"

[extra]
theme = "toggle"
toc = true
favicon = "https://avatars.githubusercontent.com/u/23194090?v=4"
comment = false

menu = [
    { name = "/diaries", url = "/diaries", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
  { name = "github", url = "https://github.com/boykush", icon = "github" },
  { name = "x-twitter", url = "https://twitter.com/boykush315", icon = "x-twitter" },
]

stylesheets = [
    "dark.css",
    "light.css",
    "fonts.css",
    "thumbnail.css"
]

[extra.analytics]
enabled = true
ga_id = "G-X6KGCVNLWP"
